study_prefix = "htn"

[sql_config]
file_names = [
    # study period
    "study_period.sql",

    # blood pressure
    "define_bp.sql",
    "table_bp.sql",

    # Diagnosis
    "define_dx.sql",
    "define_dx_essential.sql",
    "define_dx_existing.sql",
    "table_dx.sql",
    "table_prevalence.sql",
    "table_comorbidity.sql",

    # Count
    "count.sql",

    # Medication
    "define_rx.sql",
    "define_rx_exclude.sql",
    "table_rx.sql", # for sites that support MedicationRequest

    # Encounter Types
#    "define_enc_outpatient.sql",
#    "define_enc_home.sql",
#    "define_enc_office.sql",
#    "define_enc_wellness.sql",
#    "define_enc_preventive.sql",
#    "define_enc_nursing.sql",
#    "define_enc_hospice.sql",
#    "define_enc_inpatient.sql",
#    "define_enc_palliative.sql",

    # health status
#    "define_esrd.sql",
#    "define_frailty.sql",
#    "define_pregnancy.sql",
]

[export_config]
export_list = [
    "htn__count_study_period_week",
    # "htn__count_study_period_date",
    "htn__count_bp",
    "htn__count_bp_month",
    "htn__count_bp_week",
    "htn__count_bp_date",
    "htn__count_dx_month",
    "htn__count_dx_week",
    "htn__count_dx_date",
    "htn__count_prevalence_month",
    "htn__count_prevalence_week",
    "htn__count_comorbidity",
    "htn__count_comorbidity_month",
    "htn__count_comorbidity_week",
    "htn__count_comorbidity_period",
    "htn__count_comorbidity_period_month",
    "htn__count_comorbidity_period_week",
    "htn__count_rx",
    "htn__count_prevalence_rx_month"
]

